name: automerge
on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, ready_for_review ]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge when checks pass
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash