name: docs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Generate Javadoc
        run: |
          mvn -B -DskipTests=true javadoc:javadoc
      - name: Prepare gh-pages
        run: |
          rm -rf out-docs
          mkdir -p out-docs
          cp -r target/site/apidocs out-docs/javadoc || true

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out-docs
          publish_branch: gh-pages
