name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build (skip tests if already validated)
        run: mvn -B -DskipTests=true clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: "**/target/*.jar"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/target/*.jar
          generate_release_notes: true